global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["192.168.51.129:8000"] 
  
  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.51.129:9100"]
  
  - job_name: "kafka-jmx"
    static_configs:
      - targets:
          - controller-1:7081
          - controller-2:7082
          - controller-3:7083
          - kafka-1:7071
          - kafka-2:7072
          - kafka-3:7073

    