# startDelaySeconds: 0
# lowercaseOutputLabelNames: true
# lowercaseOutputLabelNames: true

# rules:
#   - pattern: "kafka_server<type=(.+)>,name=(.+)"
#     name: "kafka_server_{$1}_{$2}"
#     type: "gauge"
#   - pattern: "kafka_controller<type=(.+)>,name=(.+)"
#     name: "kafka_controller_{$1}_{$2}"
#     type: "gauge"
#   - pattern: "kafka_network<type=(.+)>,name=(.+)"
#     name: "kafka_network_{$1}_{$2}"
#     type: "gauge"    
    

startDelaySeconds: 0
lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
    name: kafka_server_$1_$2
    type: GAUGE

  - pattern: "kafka.controller<type=(.+), name=(.+)><>Value"
    name: kafka_controller_$1_$2
    type: GAUGE
